[project]
name = "EEG-Sharknado"
version = "0.1.0"
description = "EEG-Project Code - Sharknado"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "awscli>=1.43.1",
    "matplotlib>=3.10.7",
    "mne==1.10.2",
    "mne-bids==0.17.0",
    "mne-bids-pipeline==1.9.0",
    "scipy>=1.16.3",
    "torch>=2.11.0",
    "yapf>=0.43.0",
]
